sudo: required
language: clojure
lein: 2.7.1
install:
  - ./scripts/lein-modules install
  - lein deps
  - npm install
script:
  - ./scripts/test.sh $TEST
#  - ./scripts/submit-to-coveralls.sh $TEST
env:
  matrix:
  - TEST=clj
  - TEST=cljs
jdk:
  - oraclejdk8
node_js:
  - "8"
cache:
  directories:
  - "$HOME/.m2"
  - "node_modules"
addons:
  chrome: stable
